import type { Metadata } from 'next';
import { Inter as FontSans } from 'next/font/google';
import './globals.css';

import SideBarLayout from '@/app/SideBarLayout';
import HeaderLayout from '@/app/HeaderLayout';

import { ScrollArea } from '@/components/ui/scroll-area';

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const AppLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <div className="grid min-h-screen w-full md:grid-cols-[220px_1fr] lg:grid-cols-[280px_1fr]">
      <div className="hidden border-r bg-muted/40 md:block">
        <SideBarLayout />
      </div>
      <div className="flex flex-col">
        <HeaderLayout />
        <main className="flex flex-1 flex-col gap-4 p-4 lg:gap-6 lg:p-6 h-screen">
          <ScrollArea className="h-[430px] 2xl:h-full">{children}</ScrollArea>
        </main>
      </div>
    </div>
  );
};

export default AppLayout;
