import type { Metadata } from 'next';
import { Inter as FontSans } from 'next/font/google';
import './globals.css';

import { cn } from '@/lib/utils';
import AuthLayout from '@/app/AuthLayout';
import SideBarLayout from '@/app/SideBarLayout';
import HeaderLayout from '@/app/HeaderLayout';

import { ScrollArea } from '@/components/ui/scroll-area';
import { isAuthenticated } from '@/actions/auth';

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn('font-sans', fontSans.variable)}>
        {children}
      </body>
    </html>
  );
}
