import type { Metadata } from 'next';
import { Inter as FontSans } from 'next/font/google';
import './globals.css';

import { cn } from '@/lib/utils';
import AuthLayout from '@/layout/AuthLayout';
import SideBarLayout from '@/layout/SideBarLayout';
import HeaderLayout from '@/layout/HeaderLayout';

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = true;
  if (!user) return <AuthLayout>{children}</AuthLayout>;
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(' font-sans antialiased', fontSans.variable)}>
        <div className="grid min-h-screen w-full md:grid-cols-[220px_1fr] lg:grid-cols-[280px_1fr]">
          <SideBarLayout />
          <div className="flex flex-col">
            <HeaderLayout />
            <main className="flex flex-1 flex-col gap-4 p-4 lg:gap-6 lg:p-6">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
